services:
  server:
    container_name: gitea
    image: docker.gitea.com/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    extra_hosts:
      - "${AUTH_DOMAIN:?err}=${AUTH_HOST:?err}"
    labels:
      container_group: gitea
    logging:
      driver: journald
      options:
        labels: container_group
    networks:
    - local
    ports:
      - 3000:3000
      - 3022:22
    restart: unless-stopped
    volumes:
      - ${DEVSTACK_DIR:?err}/gitea/data:/data
      - ./conf/app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
