services:
  server:
    container_name: gitea
    image: docker.gitea.com/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - 3000:3000
      - 3022:22
    restart: unless-stopped
    volumes:
      - ${DEVSTACK_DIR:?err}/gitea/data:/data
      - ./conf/app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
