services:
  server:
    container_name: vault
    image: openbao/openbao:latest
    command: ['server', '-config=/openbao/config/vault.conf']
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DISABLE_MLOCK=true
      - VAULT_PG_CONNECTION_URL=${VAULT_DB_SOURCE:?err}
    extra_hosts:
      - "${AUTH_DOMAIN:?err}=${AUTH_HOST:?err}"
    healthcheck:
      test: 'wget --spider -q -T5 -S http://127.0.0.1:8200/v1/sys/health 2>&1 | grep "200 OK" > /dev/null'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    labels:
      container_group: vault
    logging:
      driver: journald
      options:
        labels: container_group
    networks:
      - local
    ports:
      - 8200:8200
    restart: unless-stopped
    volumes:
      - ./vault.conf:/openbao/config/vault.conf:ro
      - ./secrets:/openbao/secrets
